// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const mongoose = require("mongoose");

// This section contains the properties of your model, mapped to your collection's properties.
// Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
const schema = mongoose.Schema(
  {
    status: { type: String, default: "" },
    episodeId: { type: String, default: "" },
    timestamp: Date,
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "users",
    },
    clientInfos: {
      name: { type: String, default: "" },
      voice: {
        voiceName: { type: String, default: "" },
        voiceType: { type: String, default: "" },
        voiceHeight: { type: String, default: "" },
        voiceTempo: { type: String, default: "" },
      },
      adjectives: [String],
      options: [Object],
      pricing: [Object],
      price: { type: Number, default: 0 },
      textToTransform: { type: String, default: "" },
      comments: {
        commentsOrder: { type: String, default: "" },
        commentsDemo: { type: String, default: "" },
        commentsRecording: { type: String, default: "" },
      },
      descriptionForPlatforms: { type: String, default: "" },
    },
    echoesInfos: {
      nameEchoes: { type: String, default: "" },
      messageEchoes: { type: String, default: "" },
      voiceNameEchoes: { type: String, default: "" },
      textToTransformEchoes: { type: String, default: "" },
      audioEchoes: {
        extractEchoes: { type: String, default: "" },
        finalEchoes: { type: String, default: "" },
        durationEchoes: { type: Number, default: 0 },
      },
    },
  },
  {
    timestamps: false,
  }
);

module.exports = mongoose.model("episodes", schema, "episodes");
