// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const mongoose = require("mongoose");

// This section contains the properties of your model, mapped to your collection's properties.
// Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
const schema = mongoose.Schema(
  {
    identity: { type: String, default: "" },
    name: String,
    firstName: String,
    job: { type: String, default: "" },
    email: String,
    phone: String,
    hash: String,
    salt: String,
    token: String,
    reset: {
      resetPasswordToken: { type: String, default: "" },
      resetPasswordExpires: { type: Date, default: "" },
    },

    company: {
      companyName: { type: String, default: "" },
      siret: { type: String, default: "" },
      tva: { type: String, default: "" },
      address: {
        street: { type: String, default: "" },
        postalCode: { type: String, default: "" },
        city: { type: String, default: "" },
      },
    },
    episodes: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "episodes",
      },
    ],
    devis: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "devis",
      },
    ],
  },
  {
    timestamps: false,
  }
);

module.exports = mongoose.model("users", schema, "users");
